// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9hEnxXmYjfLdSFGRvHOVWSU0gdIW9vms',
    appId: '1:205615638875:web:72271d6c93f8e2bdca927e',
    messagingSenderId: '205615638875',
    projectId: 'backend-fae2d',
    authDomain: 'backend-fae2d.firebaseapp.com',
    storageBucket: 'backend-fae2d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMFv5C6ni9neV1BTr5_UlI3Go30CZ09nY',
    appId: '1:205615638875:android:f418ef30d004fb81ca927e',
    messagingSenderId: '205615638875',
    projectId: 'backend-fae2d',
    storageBucket: 'backend-fae2d.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9hEnxXmYjfLdSFGRvHOVWSU0gdIW9vms',
    appId: '1:205615638875:web:b480c04e2bc49b7aca927e',
    messagingSenderId: '205615638875',
    projectId: 'backend-fae2d',
    authDomain: 'backend-fae2d.firebaseapp.com',
    storageBucket: 'backend-fae2d.firebasestorage.app',
  );
}
